apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "example.fullname" . }}
  labels:
    app: {{ template "example.name" . }}
    instance: {{ .Release.Name }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "example.fullname" . }}
              servicePort: http