apiVersion: v1
kind: Service
metadata:
  name: {{ template "example.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.httpPort }}
  selector:
    app: {{ template "example.name" . }}
    project: devops