# Python service values

# Image
image: mmorejon/devops-python
imageTag: master
pullPolicy: Always

# Number of replicas
replicas: 2

# Service
service:
  type: ClusterIP
  httpPort: 80

# Resources
memoryRequest: 256Mi
memoryLimit: 512Mi

# Ingress
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  hostname: example.mmorejon.io