apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "python.fullname" . }}
  labels:
    app: {{ template "python.name" . }}
    project: devops
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "python.name" . }}
      project: devops
  template:
    metadata:
      labels:
        app: {{ template "python.name" . }}
        project: devops
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        resources:
          requests:
            memory: {{ .Values.memoryRequest | quote }}
          limits:
            memory: {{ .Values.memoryLimit | quote }}
        ports:
        - containerPort: 80