version: '3.6'
services:
  proxy:
    image: traefik:1.7.6-alpine
    restart: always
    command:
      - "--docker"
      - "--docker.watch"
    ports:
      - target: 80
        published: 80
        mode: host
        protocol: tcp
    volumes:
        - type: bind
          source: /var/run/docker.sock
          target: /var/run/docker.sock
  jenkins:
    build:
      context: .
    restart: always
    labels:
      - "traefik.backend=jenkins"
      - "traefik.frontend.rule=Host:devops-jenkins.mmorejon.io"
      - "traefik.port=8080"
    environment:
      - "JAVA_OPTS=-Duser.timezone=Europe/Madrid"
      - "JAVA_ARGS=-Xmx4096m -XX:MaxPermSize=2048m"
    volumes:
      - type: volume
        source: jenkins_data
        target: /var/jenkins_home
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

volumes:
  jenkins_data:
    name: jenkins_data
